Cinder support.

diff --git a/app/templates/common.sh.erb b/app/templates/common.sh.erb
--- a/app/templates/common.sh.erb
+++ b/app/templates/common.sh.erb
@@ -32,10 +32,17 @@ SWIFT_REVISION=${23}
 SWIFT_DEB_PACKAGER_URL=${24:-$SWIFT_DEB_PACKAGER_URL}
 SWIFT_RPM_PACKAGER_URL=${25:-$SWIFT_RPM_PACKAGER_URL}
 
-CONFIG_TEMPLATE_DESCRIPTION=${26}
-COOKBOOK_URL=${27}
-NODES_CONFIG_DIR=${28}
-SERVER_GROUP_JSON_CONF=${29}
+CINDER_URL=${26}
+CINDER_BRANCH=${27}
+CINDER_MERGE_TRUNK=${28}
+CINDER_REVISION=${29}
+CINDER_DEB_PACKAGER_URL=${30:-$CINDER_DEB_PACKAGER_URL}
+CINDER_RPM_PACKAGER_URL=${31:-$CINDER_RPM_PACKAGER_URL}
+
+CONFIG_TEMPLATE_DESCRIPTION=${32}
+COOKBOOK_URL=${33}
+NODES_CONFIG_DIR=${34}
+SERVER_GROUP_JSON_CONF=${35}
 
 # Setup default branches to merge if MERGE_TRUNK is checked
 # These may be overridden by some environements
@@ -43,6 +50,7 @@ NOVA_GIT_MASTER_BRANCH=${NOVA_GIT_MASTER_BRANCH:-"master"}
 GLANCE_GIT_MASTER_BRANCH=${GLANCE_GIT_MASTER_BRANCH:-"master"}
 KEYSTONE_GIT_MASTER_BRANCH=${KEYSTONE_GIT_MASTER_BRANCH:-"master"}
 SWIFT_GIT_MASTER_BRANCH=${SWIFT_GIT_MASTER_BRANCH:-"master"}
+CINDER_GIT_MASTER_BRANCH=${CINDER_GIT_MASTER_BRANCH:-"master"}
 
 # Setup default RPM packager branches
 # These may be overridden by some environements
@@ -50,6 +58,7 @@ NOVA_RPM_PACKAGER_BRANCH=${NOVA_RPM_PACKAGER_BRANCH:-"master"}
 GLANCE_RPM_PACKAGER_BRANCH=${GLANCE_RPM_PACKAGER_BRANCH:-"master"}
 KEYSTONE_RPM_PACKAGER_BRANCH=${KEYSTONE_RPM_PACKAGER_BRANCH:-"master"}
 SWIFT_RPM_PACKAGER_BRANCH=${SWIFT_RPM_PACKAGER_BRANCH:-"master"}
+CINDER_RPM_PACKAGER_BRANCH=${CINDER_RPM_PACKAGER_BRANCH:-"master"}
 
 GIT_CACHE_DIR=${GIT_CACHE_DIR:-"$HOME/.smokestack_git_cache"}
 
@@ -188,6 +197,34 @@ function get_swift_source_git {
 
 	if [[ "$SWIFT_MERGE_TRUNK" == "true" ]]; then
 		git merge $SWIFT_GIT_MASTER_BRANCH || fail "Failed to merge $SWIFT_GIT_MASTER_BRANCH."
+	fi
+
+	popd
+
+}
+
+function get_cinder_source_git {
+
+        start_metric "Git Clone Cinder"
+	git_clone "$CINDER_GIT_MASTER" "cinder_source"
+        stop_metric
+	pushd cinder_source
+	git fetch $CINDER_URL $CINDER_BRANCH || \
+		fail "Failed to git fetch branch $CINDER_BRANCH."
+	git checkout -q FETCH_HEAD || fail "Failed to git checkout FETCH_HEAD."
+
+	if [ -n "$CINDER_REVISION" ]; then
+		git checkout $CINDER_REVISION || \
+			fail "Failed to revert to revision $CINDER_REVISION."
+	else
+		CINDER_REVISION=$(git rev-parse --short HEAD)
+		[ -z "$CINDER_REVISION" ] && \
+			fail "Failed to obtain cinder revision from git."
+	fi
+	echo "CINDER_REVISION=$CINDER_REVISION"
+
+	if [[ "$CINDER_MERGE_TRUNK" == "true" ]]; then
+		git merge $CINDER_GIT_MASTER_BRANCH || fail "Failed to merge $CINDER_GIT_MASTER_BRANCH."
 	fi
 
 	popd
diff --git a/app/templates/puppet_runner.sh.erb b/app/templates/puppet_runner.sh.erb
--- a/app/templates/puppet_runner.sh.erb
+++ b/app/templates/puppet_runner.sh.erb
@@ -180,6 +180,37 @@ stop_metric
 
     fi
 
+    if [ -n "$BUILD_CINDER" ]; then
+        local CINDER_MERGE_MASTER=""
+        if [[ "$CINDER_MERGE_TRUNK" == "true" ]]; then
+            CINDER_MERGE_MASTER="true"
+        fi
+        start_metric "Build Cinder"
+        rake cinder:build_packages SOURCE_DIR="$TMP_DIR/cinder_source" \
+            SERVER_NAME="$BUILD_SERVER_NAME" \
+            RPM_PACKAGER_URL="$CINDER_RPM_PACKAGER_URL" \
+            RPM_PACKAGER_BRANCH="$CINDER_RPM_PACKAGER_BRANCH" \
+            SOURCE_URL="$CINDER_URL" \
+            SOURCE_BRANCH="$CINDER_BRANCH" \
+            GIT_MASTER="$CINDER_GIT_MASTER" \
+            GIT_MERGE_MASTER_BRANCH="$CINDER_GIT_MASTER_BRANCH" \
+            MERGE_MASTER="$CINDER_MERGE_MASTER" \
+            REVISION="$CINDER_REVISION" \
+            CACHEURL="$RPM_CACHEURL" \
+            || fail "Failed to build cinder packages."
+        stop_metric
+
+        start_metric "Build Python-Cinderclient"
+        rake cinder:build_python_cinderclient \
+            SERVER_NAME="$BUILD_SERVER_NAME" \
+            SOURCE_URL="$CINDERCLIENT_GIT_MASTER" \
+            RPM_PACKAGER_URL="$CINDERCLIENT_RPM_PACKAGER_URL" \
+            CACHEURL="$RPM_CACHEURL" \
+            || fail "Failed to build cinderclient packages."
+        stop_metric
+
+    fi
+
     # Copy hosts file to all nodes
     copy_hosts
 
diff --git a/app/templates/unittest_runner.sh.erb b/app/templates/unittest_runner.sh.erb
--- a/app/templates/unittest_runner.sh.erb
+++ b/app/templates/unittest_runner.sh.erb
@@ -17,6 +17,7 @@ function tox_cache_dir {
   echo "$PROJECT_NAME" > $CACHE_MD5_TMP
   cat tools/*requires >> $CACHE_MD5_TMP
   local MD5_SUM=$(md5sum $CACHE_MD5_TMP | cut -f 1 -d ' ')
+  rm "$CACHE_MD5_TMP"
   echo "/tmp/$PROJECT_NAME-$MD5_SUM"
 }
 
@@ -86,6 +87,7 @@ local TESTS_RUN=0
 local MSG=""
 cd $TMP_DIR
 
+#BEGIN NOVA
 if ! is_master "$NOVA_URL" "$NOVA_GIT_MASTER" "$NOVA_BRANCH"; then
   TESTS_RUN=$(( $TESTS_RUN + 1 ))
   if [ -n "$NOVA_URL" ]; then
@@ -119,7 +121,9 @@ if ! is_master "$NOVA_URL" "$NOVA_GIT_MASTER" "$NOVA_BRANCH"; then
   fi
   cache_tox "nova"
 fi
+#END NOVA
 
+#BEGIN GLANCE
 if ! is_master "$GLANCE_URL" "$GLANCE_GIT_MASTER" "$GLANCE_BRANCH"; then
 
   TESTS_RUN=$(( $TESTS_RUN + 1 ))
@@ -156,7 +160,9 @@ if ! is_master "$GLANCE_URL" "$GLANCE_GIT_MASTER" "$GLANCE_BRANCH"; then
   fi
   cache_tox "glance"
 fi
+#END GLANCE
 
+#BEGIN KEYSTONE
 if ! is_master "$KEYSTONE_URL" "$KEYSTONE_GIT_MASTER" "$KEYSTONE_BRANCH"; then
   TESTS_RUN=$(( $TESTS_RUN + 1 ))
   if [ -n "$KEYSTONE_URL" ]; then
@@ -190,7 +196,9 @@ if ! is_master "$KEYSTONE_URL" "$KEYSTONE_GIT_MASTER" "$KEYSTONE_BRANCH"; then
   fi
   cache_tox "keystone"
 fi
+#END KEYSTONE
 
+#BEGIN SWIFT
 if ! is_master "$SWIFT_URL" "$SWIFT_GIT_MASTER" "$SWIFT_BRANCH"; then
 
   TESTS_RUN=$(( $TESTS_RUN + 1 ))
@@ -227,6 +235,46 @@ if ! is_master "$SWIFT_URL" "$SWIFT_GIT_MASTER" "$SWIFT_BRANCH"; then
   fi
   cache_tox "swift"
 fi
+#END SWIFT
+
+#BEGIN CINDER
+if ! is_master "$CINDER_URL" "$CINDER_GIT_MASTER" "$CINDER_BRANCH"; then
+
+  TESTS_RUN=$(( $TESTS_RUN + 1 ))
+  if [ -n "$CINDER_URL" ]; then
+    get_cinder_source_git
+  fi
+  cd $TMP_DIR/cinder_source
+  python setup.py sdist &> sdist.out || \
+    { echo "Failed to create tarball."; cat sdist.out; exit 1; }
+  cd dist
+  tar xf cinder*.tar.gz
+  rm cinder*.tar.gz
+  cd cinder*
+  get_tox_from_cache "cinder"
+  #NOTE: temp fix for "File exists: '/tmp/cinder-tests'" errors
+  rm -Rf /tmp/cinder-tests*
+  start_metric "Cinder Unit Tests"
+  tox -epy27 &> cinder.out.log
+  local CINDER_STATUS=$?
+  stop_metric
+  start_metric "Cinder Pep8"
+  tox -epep8 &> cinder_pep8.out.log
+  local CINDER_PEP8_STATUS=$?
+  stop_metric
+  if [ "$CINDER_STATUS" -ne "0" ]; then
+    RETVAL=1
+    MSG="${MSG}Cinder tests failed. "
+    handle_venv_results Cinder cinder.out.log
+  fi
+  if [ "$CINDER_PEP8_STATUS" -ne "0" ]; then
+    RETVAL=1
+    MSG="${MSG}Cinder pep8 failed. "
+    cat cinder_pep8.out.log | grep -v env=
+  fi
+  cache_tox "cinder"
+fi
+#END CINDER
 
 if [ $RETVAL -ne 0 ]; then
   fail "$MSG"
