Quantum support.

diff --git a/app/templates/common.sh.erb b/app/templates/common.sh.erb
--- a/app/templates/common.sh.erb
+++ b/app/templates/common.sh.erb
@@ -39,10 +39,17 @@ CINDER_REVISION=${29}
 CINDER_DEB_PACKAGER_URL=${30:-$CINDER_DEB_PACKAGER_URL}
 CINDER_RPM_PACKAGER_URL=${31:-$CINDER_RPM_PACKAGER_URL}
 
-CONFIG_TEMPLATE_DESCRIPTION=${32}
-COOKBOOK_URL=${33}
-NODES_CONFIG_DIR=${34}
-SERVER_GROUP_JSON_CONF=${35}
+QUANTUM_URL=${32}
+QUANTUM_BRANCH=${33}
+QUANTUM_MERGE_TRUNK=${34}
+QUANTUM_REVISION=${35}
+QUANTUM_DEB_PACKAGER_URL=${36:-$QUANTUM_DEB_PACKAGER_URL}
+QUANTUM_RPM_PACKAGER_URL=${37:-$QUANTUM_RPM_PACKAGER_URL}
+
+CONFIG_TEMPLATE_DESCRIPTION=${38}
+COOKBOOK_URL=${39}
+NODES_CONFIG_DIR=${40}
+SERVER_GROUP_JSON_CONF=${41}
 
 # Setup default branches to merge if MERGE_TRUNK is checked
 # These may be overridden by some environements
@@ -51,6 +58,7 @@ GLANCE_GIT_MASTER_BRANCH=${GLANCE_GIT_MASTER_BRANCH:-"master"}
 KEYSTONE_GIT_MASTER_BRANCH=${KEYSTONE_GIT_MASTER_BRANCH:-"master"}
 SWIFT_GIT_MASTER_BRANCH=${SWIFT_GIT_MASTER_BRANCH:-"master"}
 CINDER_GIT_MASTER_BRANCH=${CINDER_GIT_MASTER_BRANCH:-"master"}
+QUANTUM_GIT_MASTER_BRANCH=${QUANTUM_GIT_MASTER_BRANCH:-"master"}
 
 # Setup default RPM packager branches
 # These may be overridden by some environements
@@ -59,6 +67,7 @@ GLANCE_RPM_PACKAGER_BRANCH=${GLANCE_RPM_PACKAGER_BRANCH:-"master"}
 KEYSTONE_RPM_PACKAGER_BRANCH=${KEYSTONE_RPM_PACKAGER_BRANCH:-"master"}
 SWIFT_RPM_PACKAGER_BRANCH=${SWIFT_RPM_PACKAGER_BRANCH:-"master"}
 CINDER_RPM_PACKAGER_BRANCH=${CINDER_RPM_PACKAGER_BRANCH:-"master"}
+QUANTUM_RPM_PACKAGER_BRANCH=${QUANTUM_RPM_PACKAGER_BRANCH:-"master"}
 
 GIT_CACHE_DIR=${GIT_CACHE_DIR:-"$HOME/.smokestack_git_cache"}
 
@@ -225,6 +234,34 @@ function get_cinder_source_git {
 
 	if [[ "$CINDER_MERGE_TRUNK" == "true" ]]; then
 		git merge $CINDER_GIT_MASTER_BRANCH || fail "Failed to merge $CINDER_GIT_MASTER_BRANCH."
+	fi
+
+	popd
+
+}
+
+function get_quantum_source_git {
+
+        start_metric "Git Clone Quantum"
+	git_clone "$QUANTUM_GIT_MASTER" "quantum_source"
+        stop_metric
+	pushd quantum_source
+	git fetch $QUANTUM_URL $QUANTUM_BRANCH || \
+		fail "Failed to git fetch branch $QUANTUM_BRANCH."
+	git checkout -q FETCH_HEAD || fail "Failed to git checkout FETCH_HEAD."
+
+	if [ -n "$QUANTUM_REVISION" ]; then
+		git checkout $QUANTUM_REVISION || \
+			fail "Failed to revert to revision $QUANTUM_REVISION."
+	else
+		QUANTUM_REVISION=$(git rev-parse --short HEAD)
+		[ -z "$QUANTUM_REVISION" ] && \
+			fail "Failed to obtain quantum revision from git."
+	fi
+	echo "QUANTUM_REVISION=$QUANTUM_REVISION"
+
+	if [[ "$QUANTUM_MERGE_TRUNK" == "true" ]]; then
+		git merge $QUANTUM_GIT_MASTER_BRANCH || fail "Failed to merge $QUANTUM_GIT_MASTER_BRANCH."
 	fi
 
 	popd
diff --git a/app/templates/puppet_runner.sh.erb b/app/templates/puppet_runner.sh.erb
--- a/app/templates/puppet_runner.sh.erb
+++ b/app/templates/puppet_runner.sh.erb
@@ -210,6 +210,37 @@ stop_metric
 
     fi
 
+    if [ -n "$BUILD_QUANTUM" ]; then
+        local QUANTUM_MERGE_MASTER=""
+        if [[ "$QUANTUM_MERGE_TRUNK" == "true" ]]; then
+            QUANTUM_MERGE_MASTER="true"
+        fi
+        start_metric "Build Quantum"
+        rake quantum:build_packages SOURCE_DIR="$TMP_DIR/quantum_source" \
+            SERVER_NAME="$BUILD_SERVER_NAME" \
+            RPM_PACKAGER_URL="$QUANTUM_RPM_PACKAGER_URL" \
+            RPM_PACKAGER_BRANCH="$QUANTUM_RPM_PACKAGER_BRANCH" \
+            SOURCE_URL="$QUANTUM_URL" \
+            SOURCE_BRANCH="$QUANTUM_BRANCH" \
+            GIT_MASTER="$QUANTUM_GIT_MASTER" \
+            GIT_MERGE_MASTER_BRANCH="$QUANTUM_GIT_MASTER_BRANCH" \
+            MERGE_MASTER="$QUANTUM_MERGE_MASTER" \
+            REVISION="$QUANTUM_REVISION" \
+            CACHEURL="$RPM_CACHEURL" \
+            || fail "Failed to build quantum packages."
+        stop_metric
+
+        start_metric "Build Python-Quantumclient"
+        rake quantum:build_python_quantumclient \
+            SERVER_NAME="$BUILD_SERVER_NAME" \
+            SOURCE_URL="$QUANTUMCLIENT_GIT_MASTER" \
+            RPM_PACKAGER_URL="$QUANTUMCLIENT_RPM_PACKAGER_URL" \
+            CACHEURL="$RPM_CACHEURL" \
+            || fail "Failed to build quantumclient packages."
+        stop_metric
+
+    fi
+
     # Copy hosts file to all nodes
     copy_hosts
 
diff --git a/app/templates/unittest_runner.sh.erb b/app/templates/unittest_runner.sh.erb
--- a/app/templates/unittest_runner.sh.erb
+++ b/app/templates/unittest_runner.sh.erb
@@ -276,6 +276,45 @@ if ! is_master "$CINDER_URL" "$CINDER_GIT_MASTER" "$CINDER_BRANCH"; then
 fi
 #END CINDER
 
+##BEGIN QUANTUM
+if ! is_master "$QUANTUM_URL" "$QUANTUM_GIT_MASTER" "$QUANTUM_BRANCH"; then
+
+  TESTS_RUN=$(( $TESTS_RUN + 1 ))
+  if [ -n "$QUANTUM_URL" ]; then
+    get_quantum_source_git
+  fi
+  cd $TMP_DIR/quantum_source
+  python setup.py sdist &> sdist.out || \
+    { echo "Failed to create tarball."; cat sdist.out; exit 1; }
+  cd dist
+  tar xf quantum*.tar.gz
+  rm quantum*.tar.gz
+  cd quantum*
+  get_tox_from_cache "quantum"
+  #NOTE: temp fix for "File exists: '/tmp/-tests'" errors
+  rm -Rf /tmp/quantum-tests*
+  start_metric "Quantum Unit Tests"
+  tox -epy27 &> quantum.out.log
+  local QUANTUM_STATUS=$?
+  stop_metric
+  start_metric "Quantum Pep8"
+  tox -epep8 &> quantum_pep8.out.log
+  local QUANTUM_PEP8_STATUS=$?
+  stop_metric
+  if [ "$QUANTUM_STATUS" -ne "0" ]; then
+    RETVAL=1
+    MSG="${MSG}Quantum tests failed. "
+    handle_venv_results Quantum quantum.out.log
+  fi
+  if [ "$QUANTUM_PEP8_STATUS" -ne "0" ]; then
+    RETVAL=1
+    MSG="${MSG}Quantum pep8 failed. "
+    cat quantum_pep8.out.log | grep -v env=
+  fi
+  cache_tox "quantum"
+fi
+#END QUANTUM
+
 if [ $RETVAL -ne 0 ]; then
   fail "$MSG"
 fi
