Set SERVER_NAME on torpedo/fog build tasks.
Updates the torpedo and fog build tasks so that we set SERVER_NAME
correctly. This fixes build issues in some configurations.

Also, adds an explicit failure when torpedo/fog fails to build.

diff --git a/app/templates/puppet_xen_runner.sh.erb b/app/templates/puppet_xen_runner.sh.erb
--- a/app/templates/puppet_xen_runner.sh.erb
+++ b/app/templates/puppet_xen_runner.sh.erb
@@ -77,8 +77,10 @@ stop_metric
 
     build_packages
     if [ -n "$RUN_TORPEDO" ]; then
-      rake fog:build_packages
-      rake torpedo:build_packages
+      rake fog:build_packages SERVER_NAME="$BUILD_SERVER_NAME" \
+        || fail "Failed to build fog."
+      rake torpedo:build_packages SERVER_NAME="$BUILD_SERVER_NAME" \
+        || fail "Failed to build torpedo."
     fi
 
     # Copy hosts file to all nodes
