Sync with latest Puppet/Chef template runners.

diff --git a/app/templates/puppet_vpc_runner.sh.erb b/app/templates/puppet_vpc_runner.sh.erb
--- a/app/templates/puppet_vpc_runner.sh.erb
+++ b/app/templates/puppet_vpc_runner.sh.erb
@@ -30,9 +30,8 @@ function setup {
 	cd $TMP_DIR
 
 	GIT_ASKPASS=echo \
-	git clone <%= ENV['OPENSTACK_VPC_URL'] %> openstack_vpc && \
-	cd openstack_vpc || \
-	fail "Failed to checkout openstack VPC."
+	git_clone "<%= ENV['OPENSTACK_VPC_URL'] %>" "openstack_vpc"
+	cd openstack_vpc
 
 	cp "$NODES_JSON_CONF" config/nodes.json || \
 		fail "Failed to copy nodes.json"
@@ -48,40 +47,76 @@ function run_job {
 trap "{ delete_group; cd /tmp; rm -Rf $TMP_DIR; }" INT TERM EXIT
 if rake group:create && rake group:poll; then
 
+        local NOVA_MERGE_MASTER=""
+        if [[ "$NOVA_MERGE_TRUNK" == "true" ]]; then
+        	NOVA_MERGE_MASTER="true"
+	fi
 	rake nova:build_packages SOURCE_DIR="$TMP_DIR/nova_source" \
 		RPM_PACKAGER_URL="$NOVA_RPM_PACKAGER_URL" \
 		SOURCE_URL="$NOVA_URL" \
-		SOURCE_BRANCH="$NOVA_BRANCH" || \
-		fail "Failed to build nova packages."
+		SOURCE_BRANCH="$NOVA_BRANCH" \
+		GIT_MASTER="$NOVA_GIT_MASTER" \
+		MERGE_MASTER="$NOVA_MERGE_MASTER" \
+		REVISION="$NOVA_REVISION" \
+		CACHEURL="$RPM_CACHEURL" \
+		|| fail "Failed to build nova packages."
     
+        local GLANCE_MERGE_MASTER=""
+        if [[ "$GLANCE_MERGE_TRUNK" == "true" ]]; then
+        	GLANCE_MERGE_MASTER="true"
+	fi
 	rake glance:build_packages SOURCE_DIR="$TMP_DIR/glance_source" \
 		RPM_PACKAGER_URL="$GLANCE_RPM_PACKAGER_URL" \
 		SOURCE_URL="$GLANCE_URL" \
-		SOURCE_BRANCH="$GLANCE_BRANCH" || \
-		fail "Failed to build glance packages."
-    
+		SOURCE_BRANCH="$GLANCE_BRANCH" \
+		GIT_MASTER="$GLANCE_GIT_MASTER" \
+		MERGE_MASTER="$GLANCE_MERGE_MASTER" \
+		REVISION="$GLANCE_REVISION" \
+		CACHEURL="$RPM_CACHEURL" \
+		|| fail "Failed to build glance packages."
 
-	#rake keystone:build_packages SOURCE_DIR="$TMP_DIR/keystone_source" \
-	#	DEB_PACKAGER_URL="$KEYSTONE_DEB_PACKAGER_URL" || \
-	#	RPM_PACKAGER_URL="$KEYSTONE_RPM_PACKAGER_URL" || \
-	#	fail "Failed to build keystone packages."
+        local KEYSTONE_MERGE_MASTER=""
+        if [[ "$KEYSTONE_MERGE_TRUNK" == "true" ]]; then
+        	KEYSTONE_MERGE_MASTER="true"
+	fi
+	rake keystone:build_packages SOURCE_DIR="$TMP_DIR/keystone_source" \
+		RPM_PACKAGER_URL="$KEYSTONE_RPM_PACKAGER_URL" \
+		SOURCE_URL="$KEYSTONE_URL" \
+		SOURCE_BRANCH="$KEYSTONE_BRANCH" \
+		GIT_MASTER="$KEYSTONE_GIT_MASTER" \
+		MERGE_MASTER="$KEYSTONE_MERGE_MASTER" \
+		REVISION="$KEYSTONE_REVISION" \
+		CACHEURL="$RPM_CACHEURL" \
+		|| fail "Failed to build keystone packages."
+
+        rake keystone:build_python_keystoneclient SOURCE_URL="git://github.com/openstack/python-keystoneclient.git" CACHEURL="$RPM_CACHEURL"
+
+        rake nova:build_python_novaclient SOURCE_URL="git://github.com/openstack/python-novaclient.git" CACHEURL="$RPM_CACHEURL"
 
 	# Copy hosts file to all nodes
 	copy_hosts
     
 	PUPPETMODULES_URL=$(grep "^chef_cookbook_repos" $CHEF_INSTALLER_CONF | sed -e 's/.* //g')
-	rake puppet:install PUPPETMODULES_URL=$PUPPETMODULES_URL
+	rake puppet:install SOURCE_URL="$PUPPETMODULES_URL"
+
+	rake keystone:configure
+
+	rake glance:load_images
     
 	#run Torpedo API tests (Uses the Ruby openstack-compute gem)
 	if [ -n "$RUN_TORPEDO" ]; then
-		rake torpedo SERVER_NAME=nova1 PLATFORM=FEDORA|| \
-			{ fail "Hit by Torpedo."; }
+		rake torpedo SERVER_NAME=nova1 || \
+		{ rake tail_logs; fail "Hit by Torpedo."; }
 	fi
                
 	# run smoke tests
 	if [ -n "$RUN_NOVA_SMOKE_TESTS" ]; then
-		rake nova:smoke_tests SERVER_NAME=nova1 PLATFORM=FEDORA || \
-		{ fail "Smoke tests failed."; }
+		rake nova:smoke_tests_fedora SERVER_NAME=nova1 NO_VOLUME=true || \
+		{ rake tail_logs; fail "Smoke tests failed."; }
+
+		# Only cache rpms if smoketests pass 
+		rake fedora:fill_cache CACHEURL=$RPM_CACHEURL
+
 	fi
                
 else
