Create tarballs before running unit tests.

diff --git a/app/templates/unittest_runner.sh.erb b/app/templates/unittest_runner.sh.erb
--- a/app/templates/unittest_runner.sh.erb
+++ b/app/templates/unittest_runner.sh.erb
@@ -53,6 +53,11 @@ if ! is_master "$NOVA_URL" "$MASTER_NOVA_URL" "$NOVA_BRANCH"; then
     fi
   fi
   cd $TMP_DIR/nova_source
+  python setup.py sdist &> sdist.out { echo "Failed to create tarball."; cat sdist.out; exit 1; }
+  cd dist
+  cd tar xf nova*.tar.gz
+  rm nova*.tar.gz
+  cd nova*
   ./run_tests.sh -V -f &> nova.out.log
   local NOVA_STATUS=$?
   ./run_tests.sh -V -p &> nova_pep8.out.log
@@ -80,6 +85,11 @@ if ! is_master "$GLANCE_URL" "$MASTER_GLANCE_URL" "$GLANCE_BRANCH"; then
     fi
   fi
   cd $TMP_DIR/glance_source
+  python setup.py sdist &> sdist.out { echo "Failed to create tarball."; cat sdist.out; exit 1; }
+  cd dist
+  cd tar xf glance*.tar.gz
+  rm glance*.tar.gz
+  cd glance*
   #NOTE: temp fix for "File exists: '/tmp/glance-tests'" errors
   rm -Rf /tmp/glance-tests*
   ./run_tests.sh -V -f &> glance.out.log
@@ -109,6 +119,11 @@ if ! is_master "$KEYSTONE_URL" "$MASTER_KEYSTONE_URL" "$KEYSTONE_BRANCH"; then
     fi
   fi
   cd $TMP_DIR/keystone_source
+  python setup.py sdist &> sdist.out { echo "Failed to create tarball."; cat sdist.out; exit 1; }
+  cd dist
+  cd tar xf keystone*.tar.gz
+  rm keystone*.tar.gz
+  cd keystone*
   ./run_tests.sh -V -f &> keystone.out.log
   local KEYSTONE_STATUS=$?
   ./run_tests.sh -V -p &> keystone_pep8.out.log
