Fix syntax error in sdist command.

diff --git a/app/templates/unittest_runner.sh.erb b/app/templates/unittest_runner.sh.erb
--- a/app/templates/unittest_runner.sh.erb
+++ b/app/templates/unittest_runner.sh.erb
@@ -53,7 +53,8 @@ if ! is_master "$NOVA_URL" "$MASTER_NOVA_URL" "$NOVA_BRANCH"; then
     fi
   fi
   cd $TMP_DIR/nova_source
-  python setup.py sdist &> sdist.out { echo "Failed to create tarball."; cat sdist.out; exit 1; }
+  python setup.py sdist &> sdist.out || \
+    { echo "Failed to create tarball."; cat sdist.out; exit 1; }
   cd dist
   cd tar xf nova*.tar.gz
   rm nova*.tar.gz
@@ -85,7 +86,8 @@ if ! is_master "$GLANCE_URL" "$MASTER_GLANCE_URL" "$GLANCE_BRANCH"; then
     fi
   fi
   cd $TMP_DIR/glance_source
-  python setup.py sdist &> sdist.out { echo "Failed to create tarball."; cat sdist.out; exit 1; }
+  python setup.py sdist &> sdist.out || \
+    { echo "Failed to create tarball."; cat sdist.out; exit 1; }
   cd dist
   cd tar xf glance*.tar.gz
   rm glance*.tar.gz
@@ -119,7 +121,8 @@ if ! is_master "$KEYSTONE_URL" "$MASTER_KEYSTONE_URL" "$KEYSTONE_BRANCH"; then
     fi
   fi
   cd $TMP_DIR/keystone_source
-  python setup.py sdist &> sdist.out { echo "Failed to create tarball."; cat sdist.out; exit 1; }
+  python setup.py sdist &> sdist.out || \
+    { echo "Failed to create tarball."; cat sdist.out; exit 1; }
   cd dist
   cd tar xf keystone*.tar.gz
   rm keystone*.tar.gz
